name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/images/valorantlogo_1.png
  - assets/images/pubglogo_1.jpeg
  - assets/images/rectangle_31.png
  - assets/images/pubg_11.jpeg
  - assets/images/image_1.png
  - assets/images/rectangle_33.jpeg
  - assets/images/rectangle_32.jpeg
  - assets/images/photo_room_202405010152111.png
  - assets/images/logoml_2.jpeg
  - assets/images/logoff_1.jpeg
  - assets/images/rectangle_34.jpeg
  - assets/vectors/container_2_x2.svg
  - assets/vectors/container_1_x2.svg
  - assets/vectors/container_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/images/photo_room_202405010152111.png
  - assets/images/logoml_2.jpeg
  - assets/images/photo_room_202405042013052.png
  - assets/images/photo_room_202405042155301.png
  - assets/images/photo_room_202405010152111.png

